import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'greeting': 'Hello',
          'image_ratio': 'Aspect Ratio must be 16/9',
          'login': 'Login',
          'register': 'Register',
          'create_an_account': 'Create an Account',
          'dont_have_an_account': 'Don\'t have an account?',
          'email': 'Email',
          'password': 'Password',
          'password_confirm': 'Password Confirm',
          'confirm': 'Confirm',
          'please_enter_a_valid_email': 'Please enter a valid email',
          'forget_pass': 'Forgot your password?',
          'remember': 'Remember me',
          'or_login_with': 'Or Login With',
          'personal_info': 'Personal Info',
          "next": "Next",
          "name": "Name",
          "first_name": "First Name",
          "last_name": "Last Name",
          "done": "Done",
          "religion": "Religion",
          "phone_number": "Phone Number",
          "choose": "Choose",
          "select": "Select",
          "nationality": "Nationality",
          "optional": "Optional",
          "job": "Job",
          "address_info": "Address Info",
          "city": "City",
          "Country": "Country",
          "region": "Region",
          "street": "Street",
          "building": "Building",
          "adn": "Automated address number",
          "piece_num": "Piece Number",
          "id_proof": "Identity proof",
          "id_number": "Id Number",
          "ref_number": "Refernce Number",
          "upload_id": "Upload an ID Photo",
          "upload_category_icon": "Upload Category Icon",
          "id_photo": "ID Photo",
          "id_photo_front": "Front side of ID",
          "id_photo_back": "Back side of ID",
          "upload_personal_photo": "Upload Personal Photo",
          "security": "Security",
          "otp_text_1": "Confirm Your Email",
          "otp_text_2": "Type the code that you received on the email",
          "otp_text_3": "Didn't get any code?",
          "otp_text_4": "Resend",
          "send": "Send",
          "hello": "Hello",
          "all": "All",
          "services": "Services",
          "rec_com": "Recruitment companies",
          "cl_com": "Cleaning companies",
          "cleaner": "Cleaner",
          "driver": "Driver",
          "chef": "Chef",
          "babysitter": "Babysitter",
          "nurse": "Nurse",
          "sewing": "Sewing",
          "washing": "Washing",
          "per_hour": "Per Hour",
          "per_year": "Per Year",
          "per_treatment": "Per Treatment",
          "user_type_text": "You are registering as",
          "company": "Company",
          "user": "User",
          "closest": "Closest",
          "close": "Close",
          "best": "Best",
          "cheapest": "Cheapest",
          "employee_filter_page": "Set filters for employees",
          "booking_filter_page": "Set filters for Bookings",
          "ads_filter_page": "Set filters for Advertisments",
          "age": "Age",
          "gender": "Gender",
          "male": "Male",
          "single": "Single",
          "female": "Female",
          "married": "Married",
          "marital_status": " Marital Status",
          "status": "Status",
          "employees": "Employees",
          "s_languages": "Spoken Languages",
          "apply": "Apply",
          "complete_data": "Complete this data",
          "office_warrently": "Office warranty",
          "offers": "Offers",
          "rate_view": "Rating and reviews",
          "payment": "Payment",
          "contracts": "Contracts",
          "agree": "I agree",
          "download": "Download",
          "share": "Share",
          "notifications": "Notifications",
          "invoice": "Invoice",
          "categories": "Categories",
          "create_category": "Create a new category",
          "price": "Price",
          "totla": "Total",
          "delivery": "Delivery",
          "filling_data": "Filling Data",
          "start_date": "Start Date",
          "date_of_birth": "Date of birth",
          "living_town": "Living town",
          "birth_place": "Birth place",
          "end_date": "End Date",
          "settings": "Settings",
          "owner_info": "Owner Info",
          "company_info": "Company Info",
          "company_name": "Company name",
          "company_type": "Company type",
          "url": "Url",
          "docs": "Documents",
          "write_your_email": "Write Your Email",
          "write_your_ph_num": "Write Your Phone Number",
          "reset_password": "Reset Password",
          "try_ph_num": "Try with your Phone Number",
          "try_email": "Try with your Email",
          "add_advertisment": "Add Advertisment",
          "add_employee": "Add new employee",
          "new": "new",
          "upload": "Upload",
          "photo": "Photo",
          "duration": "Duration",
          "day": "Day",
          "promotion_url": "Promotion Url",
          "company_page": "Company page",
          "external_link": "External link",
          "add": "Add",
          "added": "Added",
          "total_balance": "Total balance",
          "booking_no": "Bookings No.",
          "bookings_payments": "Bookings payments",
          "bookings": "Bookings",
          "payments": "Payments",
          "ads_payment": "Payments of Ads.",
          "ads": "Advertisments",
          "users_no": "Users No.",
          "rec_com_no": "Recruitment companies No.",
          "clean_com_no": "Cleaning companies No.",
          "reports": "Reports",
          "user_profiles": "User Profiles",
          "company_profiles": "Company Profiles",
          "no_of_children": "Children No.",
          "weight": "Weight",
          "height": "Height",
          "complexion": "Complexion",
          "passport_data": "Passport data",
          "passport_number": "Passport number",
          "issue_date": "Issue date",
          "issue_place": "Issue place",
          "expiry_date": "Expiry date",
          "work_info": "Work info",
          "other_data": "Other data",
          "cancel": "Cancel",
          "ok": "Ok",
          "search": "Search",
          "no": "No",
          "yes": "Yes",
          "is_offer": "Is there offer",
          "monthly_salery": "Monthly salery",
          "hour_salery": "Hour salery",
          "previous_work_abroad": "Previous work abroad",
          "duration_of_employment": "Duration of employment",
          "educational_certificates": "Educational certificates",
          "knowledge_of_languages": "Knowledge of languages",
          "contract_duration": "Contract duration",
          "contract_amount": "Contract amount",
          "nothing_found": "Nothing Found!!",
          "commercial_info": "Commercial information",
          "commercial_reg_number": "Commercial registration number",
          "tax_number": "Tax number",
          "license_number": "license number",
          "upload_company_logo": "Upload Company Logo",
          "recruitment": "Recruitment",
          "cleaning": "Cleaning",
          "general_info": "General Info",
          "upload_front_side_of_id": "Upload front side of ID",
          "upload_back_side_of_id": "Upload back side of ID",
          "Upload_your_passport": "Upload your passport",
          "identity_confirmation_by": "Identity confirmation by",
          "id": "ID",
          "passport": "Passport",
          "submit": "Submit",
          "successfully": "Successfully",
          "you_have_been_registered": "You have been registered",
          "your_advertisment_has_added": "Your advertisment has added",
          "your_data_have_been_completed": "Your data have been completed",
          "your_note_have_been_sent": "Your note have been sent",
          "code_has_been_sent": "code has been sent",
          "your_email_have_been_confirmed": "Your email have been confirmed",
          "the_documents_have_been_sent": "The documents have been sent",
          "add_your": "Add your",
          "edit_your": "Edit your",
          "ad": "Advertisment",
          "check_your_phone_messages": "Check Your phone messages",
          "check_your_email": "Check Your Email",
          "phone_c":
              "Messages will be sent to your phone please check the message",
          "email_c":
              "Messages will be sent to your email please check the message",
          "change_password": "Change Password",
          "current_password": "Currenr Password",
          "new_password": "New Password",
          "confirm_password": "Confirm Password",
          "save": "Save",
          "edit": "Edit",
          "delete": "Delete",
          "create": "Create",
          "name_ar": "Name in Arabic",
          "name_en": "Name in English",
          "my_ads": "My advertisments",
          "comment": "Comment",
          "refund": "Refund",
          "today": "Today",
          "yesterday": "yesterday",
          "before": "before",
          "booking_date": "Booking date",
          "specific_date": "Specific date",
          "from_to": "From - To",
          "requests": "Requests",
          "refunds": "Refunds",
          "history": "History",
          "accept": "Accept",
          "refuse": "Refuse",
          "accepted": "Accepted",
          "refused": "Refused",
          "write_your_notes": "Write your notes",
          "account_statment": "Account Statment",
          "depositor": "Depositor",
          "beneficiary": "Beneficiary",
          "amount": "Amount",
          "payment_date": "Payment Date",
          "deposit_type": "Deposit type",
          "pending": "Pending",
          "language": "Language",
          "edit_profile": "Edit Profile",
          "about_app": "About Application",
          "work_time_per_day": "Work time per day",
          "employee_added": "Employee added",
          "amount_after_disccount": "Amount after disccount"
        },
        'ar_SYR': {
          "amount_after_disccount": "السعر بعد التخفيض",
          "employee_added": "تم إضافة الموظف",
          "work_time_per_day": "وقت العمل في اليوم",
          "edit_profile": "تعديل الملف الشخصي",
          "about_app": "حول التطبيق",
          "language": "اللغة",
          "pending": "في الإنتظار",
          "depositor": "المودع",
          "beneficiary": "المستفيد",
          "amount": "المبلغ",
          "payment_date": "تاريخ الدفع",
          "deposit_type": "نوع الإيداع",
          "account_statment": "كشف الحساب",
          "accepted": "مقبول",
          "refused": "مرفوض",
          "write_your_notes": "إكتب ملاحظاتك",
          "accept": "قبول",
          "refuse": "رفض",
          "requests": "الطلبات",
          "refunds": "الاسترداد",
          "history": "السجل",
          "booking_date": "تاريخ الحجز",
          "special_date": "تاريخ محدد",
          "from_to": "من - إلى",
          "before": "مسبقاً",
          "today": "اليوم",
          "yesterday": "البارحة",
          "refund": "إسترداد",
          "comment": "ملاحظات",
          "my_ads": "إعلاناتي",
          "name_ar": "الاسم بالعربية",
          "name_en": "الاسم بالإنجليزية",
          "create": "إنشاء",
          "edit": "تعديل",
          "delete": "حذف",
          "save": "حفظ",
          "try_email": "إعادة تعيين باستخدام البريد الالكتروني",
          "check_your_phone_messages": "تفقد الرسائل في هاتفك",
          "check_your_email": "تفقد بريدك الإلكتروني",
          "phone_c": "سيتم إرسال الرسائل إلى هاتفك ، يرجى التحقق من الرسالة",
          "email_c":
              "سيتم إرسال الرسائل إلى بريدك الإلكتروني ، يرجى التحقق من الرسالة",
          "change_password": "تغيير كلمة السر",
          "current_password": "كلمة السر الحالية",
          "new_password": "كلمة السر الجديدة",
          "confirm_password": "تأكيد كلمة السر",
          "confirm": "تأكيد",
          "add_your": "أضف",
          "edit_your": "عدّل",
          "ad": "إعلانك",
          "the_documents_have_been_sent": "تم إرسال الوثائق",
          "your_email_have_been_confirmed": "لقد تم تأكيد بريدك الإلكتروني",
          "code_has_been_sent": "تم إرسال الرمز",
          "your_note_have_been_sent": "لقد تم إرسال ملاحظتك",
          "your_data_have_been_completed": "لقد اكتملت بياناتك",
          "your_advertisment_has_added": "تم إضافة إعلانك",
          "you_have_been_registered": "لقد قمت بالتسجيل",
          "successfully": "بنجاح",
          "submit": "إرسال",
          "identity_confirmation_by": "تأكيد الهوية بواسطة",
          "passport": "جواز السفر",
          "id": "الهوية الشخصية",
          "upload_front_side_of_id": "تحميل الجانب الأمامي من بطاقة الهوية",
          "upload_back_side_of_id": "تحميل الجانب الخلفي من بطاقة الهوية",
          "Upload_your_passport": "بتحميل جواز السفر",
          "general_info": "معلومات عامة",
          "cleaning": "تنظيف",
          "recruitment": "توظيف",
          "upload_company_logo": "رفع شعار الشركة",
          "commercial_info": "معلومات تجارية",
          "commercial_reg_number": "رقم السجل التجاري",
          "tax_number": "الرقم الضريبي",
          "license_number": "رقم الترخيص",
          "nothing_found": "لا يوجد أي شيء!!",
          "contract_duration": "مدة العقد",
          "contract_amount": "قيمة العقد",
          "no": "لا",
          "yes": "نعم",
          "is_offer": "هل يوجد عرض",
          "monthly_salery": "الراتب الشهري",
          "hour_salery": "الراتب في الساعة",
          "previous_work_abroad": "سبق وعمل بالخارج",
          "duration_of_employment": "مدة التوظيف",
          "educational_certificates": "الشهادات التعليمية",
          "knowledge_of_languages": "هل يوجد معرفة باللغات",
          "ok": "موافق",
          "search": "بحث",
          "cancel": "الغاء",
          "other_data": "معلومات اخرى",
          "work_info": "معلومات العمل",
          "passport_data": "بيانات جواز السفر",
          "passport_number": "رقم جواز السفر",
          "issue_date": "تاريخ المشكلة",
          "issue_place": "مكان المشكلة",
          "expiry_date": "تاريخ الانتهاء",
          "complexion": "البشرة",
          "weight": "الوزن",
          "height": "الطول",
          "no_of_children": "عدد الأولاد",
          "user_profiles": "ملفات المستخدمين الشخصية",
          "company_profiles": "ملفات الشركات الشخصية",
          "bookings_payments": "مدفوعات الحجوزات",
          "bookings": "الحجوزات",
          "reports": "التقارير",
          "booking_no": "عدد الحجوزات",
          "payments": "المدفوعات",
          "ads_payment": "دفعات الإعلانات",
          "ads": "الإعلانات",
          "users_no": "عدد المستخدم",
          "rec_com_no": "عدد شركات التوظيف",
          "clean_com_no": "عدد شركات التنظيف",
          "total_balance": "إجمالي الرصيد",
          "add": "إضافة",
          "added": "تمت الإضافة",
          "day": "يوم",
          "company_page": "صفحة الشركة",
          "external_link": "رابط خارجي",
          "promotion_url": "العنوان الترويجي",
          "duration": "المدة",
          "add_advertisment": "إضافة إعلان",
          "add_employee": "إضافة موظف جديد",
          "new": "جديد",
          "upload": "رفع",
          "photo": "صورة",
          "try_ph_num": "إعادة تعيين باستخدام رقم الهاتف",
          "reset_password": "إعادة تعيين كلمة المرور",
          "write_your_email": "اكتب بريدك الإلكتروني هنا",
          "write_your_ph_num": "اكتب رقم هاتفك هنا",
          "docs": "الوثائق",
          "company_info": "معلومات الشركة",
          "company_name": "اسم الشركة",
          "company_type": "نوع الشركة",
          "url": "الرابط",
          "owner_info": "معلومات المالك",
          "totla": "المجمل",
          "delivery": "التوصيل",
          "filling_data": "تعبئة البيانات",
          "start_date": "تاريخ البدء",
          "date_of_birth": "تاريخ الولادة",
          "living_town": "مدينة المعيشة",
          "birth_place": "مكان الولادة",
          "end_date": "تاريخ الانتهاء",
          "settings": "الإعدادات",
          "price": "السعر",
          "categories": "الفئات",
          "create_category": "أنشئ فئة جديدة",
          "download": "تحميل",
          "share": "مشاركة",
          "notifications": "الإشعارات",
          "contracts": "العقود",
          "agree": "أوافق",
          "rate_view": "التقييم والمراجعات",
          "payment": "الدفع",
          "office_warrently": "ضمان المكتب",
          "العروض": "العروض",
          "complete_data": "أكمل هذه البيانات",
          "s_languages": "اللغات المتحدث بها",
          "apply": "تطبيق",
          "employees": "الموظفون",
          "marital_status": "الحالة الاجتماعية",
          "status": "الحالة",
          "gender": "الجنس",
          "male": "ذكر",
          "single": "عازب",
          "female": "أنثى",
          "married": "متزوج",
          "employee_filter_page": "تعيين الفلاتر للموظفين",
          "booking_filter_page": "تعيين الفلاتر للحجوزات",
          "ads_filter_page": "تعيين الفلاتر للإعلانات",
          "age": "العمر",
          "closest": "إغلاق",
          "close": "Close",
          "best": "الأفضل",
          "cheapest": "الأرخص",
          "user_type_text": "أنت تقوم بالتسجيل كـ",
          "cleaner": "منظف",
          "company": "شركة",
          "user": "مستخدم",
          "driver": "سواق",
          "chef": "شيف",
          "babysitter": "جليسة أطفال",
          "nurse": "تمريض",
          "sewing": "خياطة",
          "washing": "غسل",
          "per_hour": "في الساعة",
          "per_year": "في السنة",
          "per_treatment": "في العقد",
          "services": "الخدمات",
          "all": "الكل",
          "cl_com": "شركات التنظيف",
          "rec_com": "شركات التوظيف",
          "hello": "مرحباً",
          "otp_text_3": "لم أحصل على أي رمز؟",
          "otp_text_4": "إعادة الإرسال",
          "send": "إرسال",
          "otp_text_1": "تأكيد بريدك الإلكتروني",
          "otp_text_2": "اكتب الرمز الذي تلقيته على البريد الإلكتروني",
          "security": "الأمان",
          'password_confirm': 'تأكيد كلمة السر',
          "id_proof": "تأكيد الهوية",
          "id_number": "رقم الهوية",
          "ref_number": "رقم المرجع",
          "upload_id": "تحميل صورة الهوية",
          "upload_category_icon": "رفع صورة الفئة",
          "id_photo": "صورة الهوية الشخصية",
          "id_photo_front": "الوجه الأمامي للهوية الشخصية",
          "id_photo_back": "الوجه الخلفي للهوية الشخصية",
          "upload_personal_photo": "تحميل الصورة الشخصية",
          "street": "الشارع",
          "building": "البناء",
          "adn": "رقم العنوان الآلي",
          "piece_num": "رقم القطعة",
          "city": "المدينة",
          "Country": "البلدة",
          "region": "المنطقة",
          "address_info": "تفاصيل العنوان",
          "job": "العمل",
          "nationality": "الجنسية",
          "optional": "إختياري",
          "choose": "إختر",
          "select": "إختر",
          "phone_number": "رقم الهاتف",
          "name": "الاسم",
          "first_name": "الاسم الأول",
          "last_name": "الاسم الأخير",
          "done": "تم",
          "religion": "الدين",
          "next": "التالي",
          'personal_info': 'المعلومات الشخصية',
          'greeting': 'مرحباً',
          'image_ratio': 'يجب أن تكون نسبة العرض إلى الارتفاع 16/9',
          'login': 'تسجيل الدخول',
          'register': 'التسجيل',
          'create_an_account': 'أنشئ حساباً',
          'dont_have_an_account': 'ليس لديك حساب؟',
          'email': 'البريد الإلكتروني',
          'password': 'كلمة السر',
          'please_enter_a_valid_email': 'أدخل بريداً إلكترونياً صالحاً',
          'forget_pass': 'هل نسيت كلمة السر؟',
          'remember': 'تذكر كلمة السر',
          'or_login_with': 'أو قم بالدخول بواسطة',
        },
      };
}
