import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'greeting': 'Hello',
          'login': 'Login',
          'create_an_account': 'Create an Account',
          'dont_have_an_account': 'Don\'t have an account?',
          'email': 'Email',
          'password': 'Password',
          'password_confirm': 'Password Confirm',
          'confirm': 'Confirm',
          'please_enter_a_valid_email': 'Please enter a valid email',
          'forget_pass': 'Forgot your password?',
          'remember': 'Remember me',
          'or_login_with': 'Or Login With',
          'personal_info': 'Personal Info',
          "next": "Next",
          "name": "Name",
          "done": "Done",
          "phone_number": "Phone Number",
          "choose": "Choose",
          "select": "Select",
          "nationality": "Nationality",
          "optional": "Optional",
          "job": "Job",
          "address_info": "Address Info",
          "city": "City",
          "Country": "Country",
          "region": "Region",
          "street": "Street",
          "building": "Building",
          "adn": "Automated address number",
          "piece_num": "Piece Number",
          "id_proof": "Identity proof",
          "id_number": "Id Number",
          "ref_number": "Refernce Number",
          "upload_id": "Upload an ID Photo",
          "upload_personal_photo": "Upload Personal Photo",
          "security": "Security",
          "otp_text_1": "Confirm Your Email",
          "otp_text_2": "Type the code that you received on the email",
          "otp_text_3": "Didn't get any code?",
          "otp_text_4": "Resend",
          "send": "Send",
          "hello": "Hello",
          "all": "All",
          "services": "Services",
          "rec_com": "Recruitment companies",
          "cl_com": "Cleaning companies",
          "cleaner": "Cleaner",
          "driver": "Driver",
          "chef": "Chef",
          "babysitter": "Babysitter",
          "nurse": "Nurse",
          "sewing": "Sewing",
          "washing": "Washing",
          "per_hour": "Per Hour",
          "per_treatment": "Per Treatment",
          "user_type_text": "You are registering as",
          "company": "Company",
          "user": "User",
          "closest": "Closest",
          "best": "Best",
          "cheapest": "Cheapest",
          "filter_page": "Set filters for employees",
          "age": "Age",
          "gender": "Gender",
          "male": "Male",
          "single": "Single",
          "female": "Female",
          "married": "Married",
          "marital_status": " Marital Status",
          "employees": "Employees",
          "s_languages": "Spoken Languages",
          "apply": "Apply",
          "complete_data": "Complete this data",
          "office_warrently": "Office warranty",
          "offers": "Offers",
          "rate_view": "Rating and reviews",
          "payment": "Payment",
          "contracts": "Contracts",
          "agree": "I agree",
          "download": "Download",
          "share": "Share",
          "notifications": "Notifications",
          "invoice": "Invoice",
          "categories": "Categories",
          "price": "Price",
          "totla": "Total",
          "delivery": "Delivery",
          "filling_data": "Filling Data",
          "settings": "Settings",
          "owner_info": "Owner Info",
          "company_info": "Company Info",
          "docs": "Documents",
          "write_your_email": "Write Your Email",
          "write_your_ph_num": "Write Your Phone Number",
          "reset_password": "Reset Password",
          "try_ph_num": "Try with your Phone Number",
          "try_email": "Try with your Email",
        },
        'ar_SYR': {
          "try_ph_num": "إعادة تعيين باستخدام رقم الهاتف",
          "try_email": "إعادة تعيين باستخدام البريد الالكتروني",
          "reset_password": "إعادة تعيين كلمة المرور",
          "write_your_email": "اكتب بريدك الإلكتروني هنا",
          "write_your_ph_num": "اكتب رقم هاتفك هنا",
          "docs": "الوثائق",
          "company_info": "معلومات الشركة",
          "owner_info": "معلومات المالك",
          "totla": "المجمل",
          "delivery": "التوصيل",
          "filling_data": "تعبئة البيانات",
          "settings": "الإعدادات",
          "price": "السعر",
          "categories": "الفئات",
          "download": "تحميل",
          "share": "مشاركة",
          "notifications": "الإشعارات",
          "contracts": "العقود",
          "agree": "أوافق",
          "rate_view": "التقييم والمراجعات",
          "payment": "الدفع",
          "office_warrently": "ضمان المكتب",
          "العروض": "العروض",
          "complete_data": "أكمل هذه البيانات",
          "s_languages": "اللغات المتحدث بها",
          "apply": "تطبيق",
          "employees": "الموظفون",
          "marital_status": "الحالة الاجتماعية",
          "gender": "الجنس",
          "male": "ذكر",
          "single": "عازب",
          "female": "أنثى",
          "married": "متزوج",
          "filter_page": "تعيين الفلاتر للموظفين",
          "age": "العمر",
          "closest": "الأقرب",
          "best": "الأفضل",
          "cheapest": "الأرخص",
          "user_type_text": "أنت تقوم بالتسجيل كـ",
          "cleaner": "منظف",
          "company": "شركة",
          "user": "مستخدم",
          "driver": "سواق",
          "chef": "شيف",
          "babysitter": "جليسة أطفال",
          "nurse": "تمريض",
          "sewing": "خياطة",
          "washing": "غسل",
          "per_hour": "في الساعة",
          "per_treatment": "في العقد",
          "services": "الخدمات",
          "all": "الكل",
          "cl_com": "شركات التنظيف",
          "rec_com": "شركات التوظيف",
          "hello": "مرحباً",
          "otp_text_3": "لم أحصل على أي رمز؟",
          "otp_text_4": "إعادة الإرسال",
          "send": "إرسال",
          "otp_text_1": "تأكيد بريدك الإلكتروني",
          "otp_text_2": "اكتب الرمز الذي تلقيته على البريد الإلكتروني",
          "security": "الأمان",
          'password_confirm': 'تأكيد كلمة السر',
          'confirm': 'تأكيد',
          "id_proof": "تأكيد الهوية",
          "id_number": "رقم الهوية",
          "ref_number": "رقم المرجع",
          "upload_id": "تحميل صورة الهوية",
          "upload_personal_photo": "تحميل الصورة الشخصية",
          "street": "الشارع",
          "building": "البناء",
          "adn": "رقم العنوان الآلي",
          "piece_num": "رقم القطعة",
          "city": "المدينة",
          "Country": "البلدة",
          "region": "المنطقة",
          "address_info": "تفاصيل العنوان",
          "job": "العمل",
          "nationality": "الجنسية",
          "optional": "إختياري",
          "choose": "إختر",
          "select": "إختر",
          "phone_number": "رقم الهاتف",
          "name": "الاسم",
          "done": "تم",
          "next": "التالي",
          'personal_info': 'المعلومات الشخصية',
          'greeting': 'مرحباً',
          'login': 'تسجيل الدخول',
          'create_an_account': 'أنشئ حساباً',
          'dont_have_an_account': 'ليس لديك حساب؟',
          'email': 'البريد الإلكتروني',
          'password': 'كلمة السر',
          'please_enter_a_valid_email': 'أدخل بريداً إلكترونياً صالحاً',
          'forget_pass': 'هل نسيت كلمة السر؟',
          'remember': 'تذكر كلمة السر',
          'or_login_with': 'أو قم بالدخول بواسطة',
        },
      };
}
